### ISSUE TITLE
Example for individual channel writes

### ISSUE THREAD

**Issue by Keessie** [thomasvanta/TLV5610#1]
Hi @thomasvanta ,

I'm intending to use your library with a Teensy 4.0. Thanks for making this lib publicly available.

For my use case, I'm looking into having individual channel control over all 8 channels. I was wondering which write commands are required to realise this?

Translating the data sheets' data format to SPI transfer code is a bit beyond my skill level...

**Comment by thomasvanta** [comment]
Hi there,
sadly this is a very old project and I'm not maintaining it anymore. I'm sure you will find newer implementations that will work for your purposes.

**Comment by Keessie** [comment]
Hi Thomas, 

Thanks for replying. I'll dive deep myself then:-)
